// packages/vue/src/HanaImgViewer.vue
<script setup lang="ts">
import type { CSSProperties, StyleValue } from 'vue'
import type { ViewerEvent, ViewerPhase } from './internal/viewerState'
import type { HanaImgViewerProps } from './public-types'
import { computed, nextTick, onMounted, ref, shallowRef, useAttrs, useTemplateRef, watch, watchEffect } from 'vue'
import ViewerOverlay from './internal/ViewerOverlay.vue'
import { initialViewerPhase, transitionViewerPhase } from './internal/viewerState'

defineOptions({ name: 'HanaImgViewer', inheritAttrs: false })

const props = withDefaults(
  defineProps<HanaImgViewerProps>(),
  {
    alt: '',
    minZoom: 0.5,
    maxZoom: 10,
    closeOnBackdropClick: true,
    closeOnEscape: true,
    showCloseButton: true,
    transitionDuration: 300,
  },
)

const openModel = defineModel<boolean>('open', { default: false })

const attrs = useAttrs()

const originRef = useTemplateRef<HTMLImageElement>('originRef')

const hydrated = ref(false)

const requestedTarget = shallowRef<HTMLElement | null>(null)
const activeTarget = shallowRef<HTMLElement | null>(null)

const phase = ref<ViewerPhase>(initialViewerPhase)

const originFocus = shallowRef<HTMLElement | null>(null)

const overlayMounted = computed(() => phase.value !== 'closed' && activeTarget.value !== null)
const imgAttrs = computed(() => Object.fromEntries(
  Object.entries(attrs).filter(
    ([attributeName]) =>
      attributeName !== 'class'
      && attributeName !== 'style'
      && attributeName !== 'onClick'
      && attributeName !== 'onKeydown',
  ),
))

const thumbnailStyle = computed<StyleValue>(() => [
  attrs.style,
  ...(overlayMounted.value
    ? [{ visibility: 'hidden' as CSSProperties['visibility'] }]
    : []),
])

const dispatch = (event: ViewerEvent) => {
  phase.value = transitionViewerPhase(phase.value, event)
}

const requestOpen = () => openModel.value = true

const requestClose = () => openModel.value = false

const handleThumbnailClick = (event: MouseEvent) => {
  ;(attrs.onClick as ((event: MouseEvent) => void) | undefined)?.(event)
  requestOpen()
}

const handleThumbnailKeydown = (event: KeyboardEvent) => {
  ;(attrs.onKeydown as ((event: KeyboardEvent) => void) | undefined)?.(event)
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault()
    requestOpen()
  }
}

watchEffect(() => {
  if (!hydrated.value) {
    requestedTarget.value = null
    return
  }
  requestedTarget.value = props.container === undefined ? document.body : props.container
})

watch(
  () => [openModel.value === true, requestedTarget.value, phase.value, activeTarget.value] as const,
  ([desiredOpen, target, currentPhase, currentTarget]) => {
    if (currentPhase === 'closed') {
      if (desiredOpen && target && currentTarget !== target) {
        activeTarget.value = target
        originFocus.value = originRef.value
        dispatch({ type: 'SHOW' })
      }
      else if ((!desiredOpen || !target) && currentTarget) {
        activeTarget.value = null
      }
      return
    }

    if (target !== currentTarget || !desiredOpen) {
      dispatch({ type: 'HIDE' })
      return
    }

    dispatch({ type: 'SHOW' })
  },
  { flush: 'sync' },
)

const handleOpenFinished = () => dispatch({ type: 'OPEN_FINISHED' })
const handleCloseFinished = async () => {
  dispatch({ type: 'CLOSE_FINISHED' })
  await nextTick()
  if (phase.value === 'closed') {
    activeTarget.value = null
    const focusTarget = originFocus.value
    originFocus.value = null
    focusTarget?.focus({ preventScroll: true })
  }
}

watch(phase, (next) => {
  if (next === 'closed' && !openModel.value)
    activeTarget.value = null
})

onMounted(() => {
  hydrated.value = true
})
</script>

<template>
  <img
    ref="originRef"
    v-bind="imgAttrs"
    class="hana-img-viewer-thumbnail"
    :class="attrs.class"
    :style="thumbnailStyle"
    role="button"
    tabindex="0"
    :src="src"
    :alt="alt"
    @click="handleThumbnailClick"
    @keydown="handleThumbnailKeydown"
  >

  <Teleport v-if="activeTarget && phase !== 'closed'" :to="activeTarget">
    <ViewerOverlay
      :phase="phase"
      :container="activeTarget"
      :origin-element="originRef"
      :src="src"
      :preview-src="previewSrc"
      :alt="alt"
      :min-zoom="minZoom"
      :max-zoom="maxZoom"
      :transition-duration="transitionDuration"
      :close-on-backdrop-click="closeOnBackdropClick"
      :close-on-escape="closeOnEscape"
      :show-close-button="showCloseButton"
      @request-close="requestClose"
      @open-finished="handleOpenFinished"
      @close-finished="handleCloseFinished"
    />
  </Teleport>
</template>

// packages/react/src/HanaImgViewer.tsx
import type { KeyboardEvent as ReactKeyboardEvent, MouseEvent as ReactMouseEvent } from 'react'

import type { HanaImgViewerProps } from './public-types'

import {
  useCallback,
  useLayoutEffect,
  useReducer,
  useRef,
  useState,
  useSyncExternalStore,
} from 'react'
import { ViewerOverlay } from './internal/ViewerOverlay'
import { initialViewerState, viewerReducer } from './internal/viewerReducer'

const subscribeToHydration = (): (() => void) => () => {}
const getClientSnapshot = (): boolean => true
const getServerSnapshot = (): boolean => false

export const HanaImgViewer = ({
  src,
  previewSrc,
  alt = '',
  open,
  defaultOpen = false,
  onOpenChange,
  container,
  minZoom = 0.5,
  maxZoom = 10,
  transitionDuration = 300,
  closeOnBackdropClick = true,
  closeOnEscape = true,
  showCloseButton = true,
  className,
  style,
  ...rest
}: HanaImgViewerProps) => {
  const [isControlled] = useState(() => open !== undefined)
  const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen)
  const isHydrated = useSyncExternalStore(
    subscribeToHydration,
    getClientSnapshot,
    getServerSnapshot,
  )
  const [activeContainer, setActiveContainer] = useState<HTMLElement | null>(
    null,
  )
  const [viewerState, dispatch] = useReducer(viewerReducer, initialViewerState)
  const originRef = useRef<HTMLImageElement>(null)
  const originFocusRef = useRef<HTMLElement | null>(null)
  const restoreFocusRef = useRef(false)
  const desiredOpen = isControlled ? open === true : uncontrolledOpen
  const phase = viewerState.phase
  const desiredOpenRef = useRef(desiredOpen)
  const requestedContainer
    = isHydrated
      ? container === undefined
        ? document.body
        : container
      : null

  useLayoutEffect(() => {
    desiredOpenRef.current = desiredOpen
  }, [desiredOpen])

  const requestOpenChange = useCallback(
    (nextOpen: boolean) => {
      if (isControlled) {
        if (desiredOpen !== nextOpen)
          onOpenChange?.(nextOpen)
        return
      }

      if (desiredOpenRef.current === nextOpen)
        return

      desiredOpenRef.current = nextOpen
      setUncontrolledOpen(nextOpen)
      onOpenChange?.(nextOpen)
    },
    [desiredOpen, isControlled, onOpenChange],
  )

  const requestOpen = useCallback(() => {
    requestOpenChange(true)
  }, [requestOpenChange])

  const requestClose = useCallback(() => {
    requestOpenChange(false)
  }, [requestOpenChange])

  const finishOpening = useCallback(() => {
    dispatch({ type: 'OPEN_FINISHED' })
  }, [])

  const finishClosing = useCallback(() => {
    restoreFocusRef.current = true
    dispatch({ type: 'CLOSE_FINISHED' })
  }, [])

  useLayoutEffect(() => {
    if (phase === 'closed') {
      if (restoreFocusRef.current) {
        restoreFocusRef.current = false
        const capturedFocus = originFocusRef.current
        originFocusRef.current = null
        capturedFocus?.focus({ preventScroll: true })
      }

      if (desiredOpen && requestedContainer) {
        originFocusRef.current = originRef.current
        // Portal ownership can only be committed after the client container exists.
        // eslint-disable-next-line react/set-state-in-effect
        setActiveContainer(requestedContainer)
        dispatch({ type: 'SHOW' })
      }
      else if (activeContainer) {
        // Release the completed portal before accepting a new container.
        // eslint-disable-next-line react/set-state-in-effect
        setActiveContainer(null)
      }
      return
    }

    if (!requestedContainer || requestedContainer !== activeContainer) {
      restoreFocusRef.current = true
      dispatch({ type: 'HIDE' })
      return
    }

    if (!desiredOpen) {
      dispatch({ type: 'HIDE' })
      return
    }

    dispatch({ type: 'SHOW' })
  }, [activeContainer, desiredOpen, phase, requestedContainer])

  const handleThumbnailClick = (event: ReactMouseEvent<HTMLImageElement>) => {
    rest.onClick?.(event)
    requestOpen()
  }

  const handleThumbnailKeyDown = (
    event: ReactKeyboardEvent<HTMLImageElement>,
  ) => {
    rest.onKeyDown?.(event)
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault()
      requestOpen()
    }
  }

  const overlayPhase
    = viewerState.phase === 'closed' ? null : viewerState.phase
  const isOverlayMounted = overlayPhase !== null && activeContainer !== null

  return (
    <>
      <img
        ref={originRef}
        {...rest}
        className={`hana-img-viewer-thumbnail${className ? ` ${className}` : ''}`}
        style={{
          ...style,
          visibility: isOverlayMounted ? 'hidden' : style?.visibility,
        }}
        src={src}
        alt={alt}
        /* eslint-disable-next-line jsx-a11y/no-noninteractive-element-to-interactive-role */
        role="button"
        tabIndex={0}
        onClick={handleThumbnailClick}
        onKeyDown={handleThumbnailKeyDown}
      />

      {overlayPhase && activeContainer
        ? (
            <ViewerOverlay
              phase={overlayPhase}
              container={activeContainer}
              originRef={originRef}
              src={src}
              previewSrc={previewSrc}
              alt={alt}
              minZoom={minZoom}
              maxZoom={maxZoom}
              transitionDuration={transitionDuration}
              closeOnBackdropClick={closeOnBackdropClick}
              closeOnEscape={closeOnEscape}
              showCloseButton={showCloseButton}
              onRequestClose={requestClose}
              onOpenFinished={finishOpening}
              onCloseFinished={finishClosing}
            />
          )
        : null}
    </>
  )
}

export default HanaImgViewer
